### ISSUE TITLE
[Enhancement] Support Quilt Mappings

### ISSUE THREAD

**Issue by ix0rai** [MaxPixelStudios/MinecraftDecompiler#130]
Support should be added for https://github.com/QuiltMC/quilt-mappings, a collection of mappings based on Yarn using the [hashed](https://github.com/QuiltMC/mappings-hasher) format instead of intermediary.

**Comment by XiaoPangxie732** [comment]
Since Quilt mappings use the Tiny format, MCD should already support it.
Please feel free to report any issues you encounter

**Comment by ix0rai** [comment]
lovely, thanks!

**Comment by XiaoPangxie732** [comment]
btw, there is a known issue when using quilt mappings with option `-r`
that option would regenerate all variable names not provided by mappings, and would also check if the name is duplicated(to avoid the generator generating names that duplicate with mappings).
however, many lambda methods in quilt mappings have var names that duplicate with methods that contain them, which would lead the checker to issue lots of warnings
you can choose to completely trust the mappings by not passing `-r`, I can't fix this because that's not the problem on my end.
